Fix `Formatter.functionName` TypeError for arrow functions
When called with an arrow function as parameter it threw a TypeError.

    Formatter.functionName((a) => a)

The regular expression that matches the name from the function
declaration string doesn't care about arrow function syntax, thus it
didn't
match anything, `.match` returned `null` and `null[1]` threw:

    TypeError: Cannot read property '1' of null